// SPDX-License-Identifier: MIT
// Auto-generated by unfold v0.1.0
// unfold 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2 --chain mainnet --export foundry

pragma solidity ^0.8.19;

import {Test} from "forge-std/Test.sol";

interface IWETH9 {
    function name() external view returns (string arg0);
    function approve(address guy, uint256 wad) external returns (bool arg0);
    function totalSupply() external view returns (uint256 arg0);
    function transferFrom(address src, address dst, uint256 wad) external returns (bool arg0);
    function withdraw(uint256 wad) external;
    function decimals() external view returns (uint8 arg0);
    function balanceOf(address arg0) external view returns (uint256 arg0);
    function symbol() external view returns (string arg0);
    function transfer(address dst, uint256 wad) external returns (bool arg0);
    function deposit() external payable;
    function allowance(address arg0, address arg1) external view returns (uint256 arg0);
}

contract WETH9Test is Test {
    IWETH9 public target;

    function setUp() public {
        vm.createSelectFork(vm.envString("MAINNET_RPC_URL"));
        target = IWETH9(0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2);
    }

    function test_example() public view {
        assertGt(target.totalSupply(), 0);
    }
}
